apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: dhruv4023/auth-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password
            - name: DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: database-uri
            - name: DB_URL
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@$(DATABASE_URI)"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-server
  # type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
