apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
  labels:
    app: main-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-server
  template:
    metadata:
      labels:
        app: main-server
    spec:
      containers:
        - name: main-server
          image: dhruv4023/main-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: DB_NAME
              value: main_db
            - name: DB_HOST
              value: mysql-service
            - name: AUTH_API_END
              value: http://auth-service:5001
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password

---
apiVersion: v1
kind: Service
metadata:
  name: main-server-service
spec:
  selector:
    app: main-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
